#!/usr/bin/env python3
"""Card titles must be readable, stable and never empty.

Three agents store their session title in three different places, so
`SessionTitle` is the single derivation all three go through. Its failure modes
are silent — a card just shows the wrong string — so pin them down:

  * Claude Code has no title field; its card used to show `cwd`'s last path
    component, so five sessions in one project all read "ClaudeBar".
  * A transcript's `user` stream is full of plumbing (`<local-command-caveat>`,
    `/clear` wrappers, `<history>` injections). Any of it reaching a card is a
    bug that no compiler catches.
  * Truncation must not split a grapheme or leave "标题，…" dangling.

Runs against the production `SessionTitle` source, no app launch.
"""
from pathlib import Path
import subprocess
import tempfile

root = Path(__file__).resolve().parents[1]
source = (root / 'Sources/ClaudeBar/Utils/SessionTitle.swift').read_text()

swift = r'''
import Foundation

SOURCE_EOF

@main struct Regression {
    static func main() {
        // 1. Claude Code: no authored title, a real first prompt wins over the
        //    folder — this is the whole point of the change.
        // The real prompt this change was written for: CJK, long, and it must
        // neither be shown as the folder nor be cut so hard it loses meaning.
        let cc = SessionTitle(firstPrompt: "看看这个实施计划，现在都完成了吗，当前是什么进度",
                              folder: "ClaudeBar")
        precondition(cc.display != "ClaudeBar", "the folder must not win over a real prompt")
        precondition(cc.display.hasSuffix("…"), "an over-budget CJK prompt must be shortened")
        precondition(cc.display.count >= 14, "shortening must not gut the title; got \(cc.display)")

        // A Latin title of the same visual length gets proportionally more
        // characters — this is the whole reason the cap is a width, not a count.
        let latin = SessionTitle(authored: "OpenClaw configuration error", folder: "x")
        precondition(latin.display == "OpenClaw configuration error",
                     "a 28-char Latin title fits the budget whole; got \(latin.display)")
        let cjk = SessionTitle(firstPrompt: String(repeating: "字", count: 28), folder: "x")
        precondition(cjk.display.count < 20,
                     "the same 28 characters in CJK must be cut; got \(cjk.display.count)")

        // 2. A session with no usable prompt still shows something navigable.
        let bare = SessionTitle(folder: "Neo")
        precondition(bare.display == "Neo", "the folder is the last resort; got \(bare.display)")
        let nothing = SessionTitle()
        precondition(nothing.display == "session", "an empty session must not render blank")

        // 3. Authored titles outrank derived ones (Codex / Cursor).
        // 30 characters, so it wins *and* gets shortened to the cap. Real
        // Cursor titles do run long ("CM cloud organize concurrency"), which is
        // why the cap applies to authored titles too.
        let cursor = SessionTitle(authored: "CM cloud organize concurrency", folder: "cmcc_skills")
        precondition(cursor.display.hasPrefix("CM cloud organize"), "Cursor's own title must win; got \(cursor.display)")
        precondition(!cursor.display.contains("cmcc_skills"), "the folder must not leak in")
        let shortAuthored = SessionTitle(authored: "OpenClaw configuration error", folder: "openclaw")
        precondition(shortAuthored.display == "OpenClaw configuration error",
                     "a short authored title is shown whole; got \(shortAuthored.display)")

        // 4. Transcript plumbing must never become a title.
        let noise = [
            "<local-command-caveat>Caveat: The messages below were generated by the user",
            "<command-name>/clear</command-name> <command-message>clear</command-message>",
            "<local-command-stdout>Set effort level to ultracode (this session only)",
            "<history> user: 用一句话自我介绍 assistant: 我是 Claude",
        ]
        // These are exactly the records the transcript scan rejects; assert the
        // condense step would also refuse to show them as-is.
        for line in noise {
            let out = SessionTitle.condense(line)
            precondition(!out.hasPrefix("<"), "wrapper tags must be stripped; got \(out)")
        }

        // 5. Real prompts survive condensing intact (only whitespace changes).
        let real = SessionTitle.condense("  在连接模块能不能实现\n实时的检测   airpod 的状态？ ")
        precondition(real == "在连接模块能不能实现 实时的检测 airpod 的状态？",
                     "condense must flatten whitespace but keep the words; got \(real)")

        // 6. Markdown markers carry no meaning in a title.
        precondition(SessionTitle.condense("## 修复 `登录页` **闪烁**") == "修复 登录页 闪烁",
                     "markdown marks must be stripped")

        // 7. "a < b" is not a tag.
        let math = SessionTitle.condense("if a < b then swap")
        precondition(math.contains("a < b"), "a bare less-than must survive; got \(math)")

        // 8. Truncation never splits a grapheme and drops trailing punctuation.
        let emoji = SessionTitle.shorten(String(repeating: "🐳", count: 40))
        precondition(emoji.allSatisfy { $0 == "🐳" || $0 == "…" }, "a grapheme must never be split")
        precondition(emoji.hasSuffix("…"), "an over-long emoji title must still be shortened")
        let punct = SessionTitle.shorten(String(repeating: "字", count: 40) + "，后面还有")
        precondition(!punct.hasSuffix("，…"), "a dangling comma before the ellipsis reads as a typo; got \(punct)")
        precondition(SessionTitle.shorten("短标题") == "短标题", "short titles pass through untouched")
        precondition(SessionTitle.shorten("Fix the login flicker") == "Fix the login flicker",
                     "a short Latin title must never gain an ellipsis")

        // 9. The two-part card header: `folder | title` with an independent
        //    budget per half, so a long folder cannot crowd out the title.
        let split = SessionTitle(firstPrompt: "修复登录页闪烁的问题并且补齐暗色主题", folder: "ClaudeBar")
        precondition(split.cardLabel.folder == "ClaudeBar", "the folder half must be the folder")
        precondition(!split.cardLabel.title.isEmpty, "the title half must carry the prompt")
        precondition(!split.cardLabel.title.contains("ClaudeBar"), "halves must not overlap")
        let longFolder = SessionTitle(firstPrompt: "Fix it", folder: "a-very-long-project-directory-name-here")
        let label = longFolder.cardLabel
        precondition(SessionTitle.condense(label.folder).count < 40,
                     "the folder half gets its own tighter budget; got \(label.folder)")
        precondition(label.title == "Fix it", "the title half must survive a long folder")

        // 10. A session with no title must not render "folder | folder".
        let folderOnly = SessionTitle(folder: "Neo")
        precondition(folderOnly.cardLabel.title.isEmpty,
                     "no title half when the folder is all we have; got \(folderOnly.cardLabel.title)")
        precondition(folderOnly.cardLabel.accessibilityText == "Neo", "spoke form must not repeat")

        // 11. The spoken form uses a comma, never the drawn middle dot.
        precondition(label.accessibilityText == "\(label.folder)，\(label.title)",
                     "a screen reader should hear a pause, not a '·'")

        // 12. Cursor's subtitle is budgeted separately from the title.
        let sub = SessionTitle(authored: "T", folder: "f",
                               subtitle: "Edited style_judge.txt, process_pipeline2.py, mem_judge_normal.py")
        precondition(!sub.cardSubtitle.isEmpty, "a non-empty subtitle must survive")
        precondition(sub.cardSubtitle.hasSuffix("…"), "an over-long subtitle must be shortened")
        precondition(SessionTitle(subtitle: "   ").cardSubtitle.isEmpty,
                     "whitespace-only subtitles must render as absent")

        print("PASS: title chain (prompt > folder > session), authored wins, wrappers stripped, "
              + "\(Int(SessionTitle.maxWidth))pt budget (CJK cut, Latin kept), punctuation trimmed, emoji intact, "
              + "two-part header with independent folder/title/subtitle budgets")
    }
}
'''.replace('SOURCE_EOF', source)
with tempfile.TemporaryDirectory(prefix='claudebar-title-tests-') as folder:
    path = Path(folder) / 'Regression.swift'
    path.write_text(swift)
    binary = Path(folder) / 'regression'
    subprocess.run(['swiftc', '-parse-as-library', str(path), '-o', str(binary)], check=True)
    subprocess.run([str(binary)], check=True)
