#!/usr/bin/env python3
"""Regenerate the 中国天气网 cityid table (`CNWeatherCityTable.swift`).

Weather's keyless fallback addresses cities by a nine-digit `weather_index` id,
not by name. The source's own name search (`toy1.weather.com.cn/search`) used to
do the mapping, but it now answers `()` for every Chinese city name — so the
lookup is frozen into the binary instead.

The table is built from the *province → city* tree that still answers:

    https://www.weather.com.cn/data/city3jdata/china.html          (province)
    https://www.weather.com.cn/data/city3jdata/provshi/<p>.html     (its cities)

Both return `{"code": "name"}` JSON and need a weather.com.cn referer. Codes are
*pure numeric*, not the documented `101xxxyy` — 上海 is province `10102`, 杭州 is
`10121` with city code `01`.

A tree entry's id cannot be computed from its codes. For an ordinary
prefecture, `<province><city>` is one short (杭州 `1012101` → id `101210101`,
standard `101xxxyy00` = 8 digits); for a direct-controlled municipality it is one
long (北京 `10101` → id `101010100`, `02` digits) and the city code is a literal
`"00"`. Rather than reverse-engineer a rule that would be wrong on the next
region, this script **probes both candidate suffixes (`00`, `01`) against
`weather_index` and keeps whichever answers 200** — the same check the app's
fallback depends on, run 348 times, once.

Output is the `json` literal inside `Sources/ClaudeBar/Utils/CNWeatherCityTable.swift`
(the file is otherwise fixed boilerplate, so this script writes it whole).

Prefecture level only: the tree's deepest layer is the city, and a district name
(浦东新区) is deliberately absent — it falls through to Open-Meteo. Run this only
when cities are added or renamed; `Tools/` is not shipped.
"""
import json
import subprocess
import time
from pathlib import Path

BASE = "https://www.weather.com.cn/data/city3jdata"
DESK = ["-H", "Referer: http://www.weather.com.cn/", "-H", "User-Agent: Mozilla/5.0"]
OUTPUT = Path(__file__).resolve().parents[1] / "Sources/ClaudeBar/Utils/CNWeatherCityTable.swift"


def fetch(url, tries=3):
    """GET a JSON endpoint, retrying the CDN's occasional non-JSON reply."""
    for _ in range(tries):
        result = subprocess.run(["curl", "-sSL", "--noproxy", "*", "-m", "10", *DESK, url],
                                capture_output=True)
        text = result.stdout.decode("utf-8", "replace").strip()
        if text.startswith("{"):
            try:
                return json.loads(text)
            except json.JSONDecodeError:
                pass
        time.sleep(0.4)
    return None


def resolves(city_id):
    """Whether `weather_index` answers 200 for this id — the only authority on
    which candidate suffix is the real one."""
    result = subprocess.run(["curl", "-sS", "--noproxy", "*", "-m", "8", "-o", "/dev/null",
                             "-w", "%{http_code}", *DESK,
                             f"http://d1.weather.com.cn/weather_index/{city_id}.html"],
                            capture_output=True)
    return result.stdout.decode().strip() == "200"


def build():
    provinces = fetch(f"{BASE}/china.html")
    if not provinces:
        raise SystemExit("china.html unavailable")
    table, misses = {}, []
    for province_code, province in sorted(provinces.items()):
        cities = fetch(f"{BASE}/provshi/{province_code}.html")
        if not cities:
            misses.append((province, "provshi"))
            continue
        for city_code, city in cities.items():
            stem = province_code + ("01" if city_code == "00" else city_code)
            chosen = next((stem + suffix for suffix in ("00", "01") if resolves(stem + suffix)), None)
            if chosen:
                table[city] = chosen
            else:
                misses.append((city, stem))
    return table, misses


def main():
    table, misses = build()
    body = json.dumps(dict(sorted(table.items())), ensure_ascii=False, indent=4)
    body = "\n".join("    " + line for line in body.splitlines())
    OUTPUT.write_text(
        "import Foundation\n\n"
        "/// 中国天气网 cityid table for `WeatherCNFetcher`, generated by\n"
        "/// `Tools/gen-cn-weather-cities.py` — **do not edit by hand**.\n"
        "///\n"
        "/// The source's own name search (`toy1.weather.com.cn/search`) stopped\n"
        "/// resolving Chinese city names, so the lookup is kept here instead. Keys are\n"
        "/// prefecture-level city names (no district level, no 市 suffix); values are the\n"
        "/// `weather_index` ids that still answer 200. A name that is missing or renamed\n"
        "/// falls through to Open-Meteo rather than guessing.\n"
        "enum CNWeatherCityTable {\n"
        "    /// Kept as text (not a `[String: String]`) so the weather regression probe\n"
        "    /// can compile it from source with no bundle, and so a decode failure\n"
        "    /// degrades to \"no city found\" instead of trapping on launch.\n"
        "    static let json = \"\"\"\n"
        f"{body}\n"
        "\"\"\"\n"
        "}\n")
    print(f"{OUTPUT}: {len(table)} cities")
    if misses:
        print(f"{len(misses)} unresolvable: {misses[:10]}")


if __name__ == "__main__":
    main()
