// Generated by Tools/render-greeting-preview.py from Interaction.swift.
// Do not edit: the renderer rebuilds this from the production file every run,
// so the fixture cannot drift onto a stub the app does not actually have.

struct HoverState: ViewModifier {
    @Binding var isHovered: Bool

    func body(content: Content) -> some View {
        content
            .onHover { hovering in
                if ScrollHoverGate.isDeferring { return }
                if isHovered != hovering { isHovered = hovering }
            }
    }
}

extension View {
    /// Drive `isHovered` from pointer movement, animated with the theme spring.
    func hoverState(_ isHovered: Binding<Bool>) -> some View {
        modifier(HoverState(isHovered: isHovered))
    }

    /// Drop hover writes for the duration of a flick, then reconcile once.
    ///
    /// A grid of tiles that each own a hover flag lays out once per tile the
    /// pointer crosses. The flag is the one in `ScrollHoverGate`; this is the
    /// scroll view's half of it.
    func scrollHoverGate() -> some View {
        modifier(ScrollHoverGateModifier())
    }
}

struct RollingNumberModifier: ViewModifier {
    var enabled: Bool = true
    /// The rendered figure, and the roll's transition key: the transaction opens
    /// because *this* number changed, not because some value in the view
    /// happened to tick.
    ///
    /// **Not optional, and not defaulted.** A modifier is handed an opaque
    /// `_ViewModifier_Content`, not the `Text` it wraps — the erasure cannot be
    /// cast back or reflected, and `String(describing:)` of it is identical for
    /// every wrapping — so the modifier cannot read the number out of its own
    /// content and the caller has to state it. The previous shape (`String? = nil`
    /// with a `String(describing: Self.self)` fallback) was worse than a
    /// compile error: the fallback is constant, so no transaction closure was
    /// ever entered and every site that passed nothing rolled in silence.
    var figure: String
    /// Whether this figure rolls at all.
    ///
    /// The digit roll is a transition, so it runs on its own display cycle every
    /// time the number changes — for a 1 Hz reading that is a redraw of the
    /// surface per tick, whether or not anyone is looking at it. These are the
    /// figures that must **not** roll:
    ///
    /// - **a surface nobody is looking at.** The island's panel is mounted on
    ///   every display, over full-screen apps, forever; its collapsed wings tick
    ///   with the sampler. Rolling a number no one can see buys a per-tick
    ///   display cycle for nothing. The owners already track this
    ///   (`UIWakePolicy.hasVisibleWindow`, `surfaceIsVisible` in a `body`); the
    ///   figure asks via `rolls` instead of each owner remembering to gate.
    /// - **a value fed at >1 Hz.** The resource strip's CPU / GPU / 内存 / 硬盘
    ///   heroes sample as often as once a second while a detail popover is open.
    ///   At that rate the transition never settles: the tile is mid-roll when the
    ///   next reading lands, so it never shows a readable frame and it redraws
    ///   the whole card per sample. Coat every other figure in the app.
    ///
    /// A figure that is *not* rolling still updates; it just swaps, and it does
    /// not keep an animated transaction alive between readings.
    var rolls: Bool = true

    /// What the roll's transition is keyed on.
    ///
    /// `.numericText` says what happens to the glyphs **during a transition**;
    /// it does not create one. SwiftUI runs a content transition only when the
    /// change arrives inside an animation transaction (`withAnimation`, or an
    /// `.animation` SwiftUI itself opened). A plain state write from a 1 Hz
    /// sampler — what feeds almost every figure in this app — arrives in a
    /// *non-animated* transaction, so the digits swapped instantly and the roll
    /// was invisible in the running app.
    ///
    /// The fix used to be an implicit `.animation(_:value:)` on each figure, and
    /// that had a real cost: keyed on a value the sampler updates once a second,
    /// it opened a *fresh* animated transaction on every tick. While any
    /// transaction is in flight, every display cycle re-runs the whole hosting
    /// view's layout and display list — not only the cycles where the
    /// interpolated property moves. Measured on the dashboard:
    /// `+[NSAnimationContext runAnimationGroup:]` inside `NSHostingView.layout()`
    /// for 31 % of main-thread samples with it, 13 % without
    /// (docs/technical/08-performance.md).
    ///
    /// So the transaction is opened once here, keyed on the **rendered value**,
    /// rather than by a modifier sitting on a per-poll input. It still only runs
    /// when a figure actually changed, nothing stays resident on a 1 Hz value,
    /// and the app keeps exactly one definition of the roll. Doing it here rather
    /// than at each call site is also the only form a `Text` can take:
    /// `withAnimation` needs a data source to write to, and a figure is usually a
    /// *computed string* handed to a leaf — `RollingNumberText(UsageStats.formatTokens(n))`
    /// has no source to write to and no way to wrap its parent's update.
    struct Transition: Equatable {
        var value: String
        /// Reduce Motion makes the roll an identity transition: the value still
        /// updates, it just stops sliding.
        var reduceMotion: Bool
    }

    @Environment(\.accessibilityReduceMotion) private var reduceMotion

    @Environment(\.surfaceIsVisible) private var surfaceIsVisible

    func body(content: Content) -> some View {
        if enabled {
            content
                .monospacedDigit()
                .contentTransition(reduceMotion || !rolls || !surfaceIsVisible
                                   ? .identity : .numericText(countsDown: true))
                .transaction(value: transition) { transaction in
                    // The whole gate, not just the environment half: `rolls:
                    // false` and an invisible surface must not install an
                    // animation either — the key still changes on every
                    // reading, so a guard that read only `reduceMotion` would
                    // keep an animated transaction alive per tick for exactly
                    // the figures that opted out of rolling.
                    guard !reduceMotion, rolls, surfaceIsVisible,
                          transaction.animation == nil else { return }
                    transaction.animation = Theme.Animation.roll
                }
        } else {
            content
        }
    }

    /// Keyed on the rendered value, so it is `Equatable` without the modifier
    /// having to know the figure's type.
    private var transition: Transition {
        Transition(value: figure,
                   reduceMotion: reduceMotion || !rolls || !surfaceIsVisible)
    }
}

extension View {
    /// Give a figure the island's per-digit roll.
    ///
    /// Use it on the `Text` that *renders the number* — a bare count, a
    /// percentage, a token figure, or a sentence with a figure inside it (the
    /// transition rolls only the digits, so the surrounding copy stays put).
    /// Do **not** put it on a container: the roll belongs to the leaf that
    /// draws the digits, the same way the island's own figures are leaves.
    ///
    /// `figure` is the rendered value and is what the roll is keyed on, so the
    /// transaction opens only when the figure moves. It is the first parameter
    /// and it has **no default** on purpose: a `ViewModifier` is handed an
    /// opaque `_ViewModifier_Content`, not the `Text` it wraps — that erasure
    /// cannot be cast back, cannot be reflected, and `String(describing:)` of it
    /// is the same for every wrapping — so this modifier cannot read the number
    /// out of its own content. A site that says nothing would silently roll
    /// nothing at all: the transaction's key would be the type name, which never
    /// changes, so the closure that installs `Theme.Animation.roll` would never
    /// be entered and `.numericText` would have no animation to run in. Pass the
    /// same expression the label renders:
    ///
    ///     Text("已选 \(n) 项").rollingNumber("已选 \(n) 项")
    ///     Text(open ? opener : inlineValue).rollingNumber(open ? opener : inlineValue)
    ///
    /// (Both forms are what the app uses; `RollingNumberText` is the same thing
    /// pre-composed and remains the house style for a figure that is a value.)
    ///
    /// Pass `enabled: false` when the same `Text` sometimes shows a figure and
    /// sometimes a label (a JSON value that is a number only in one kind).
    ///
    /// Reduce Motion turns the roll into an identity transition; the value
    /// still updates, it just stops sliding.
    ///
    /// `rolls: false` keeps the figure live but drops the transition — for a
    /// reading that arrives faster than the roll can settle (the resource
    /// strip's 1 Hz sensors) or for a surface no one is looking at. See
    /// `RollingNumberModifier.rolls`.
    ///
    /// A call site that *is* already inside its own animation leaves this
    /// alone: the transform checks `transaction.animation == nil` before it
    /// installs the roll, so an upstream spring owns the change instead of
    /// nesting a second animation inside it.
    func rollingNumber(_ figure: String, enabled: Bool = true,
                       rolls: Bool = true) -> some View {
        modifier(RollingNumberModifier(enabled: enabled, figure: figure, rolls: rolls))
    }
}
