#!/usr/bin/env python3
"""Render the production status sheet at wide/narrow widths in both themes.
Only the store-dependent wrapper is omitted. Fixtures are synthetic; no account
files, live services or persistent preferences are read or changed.
"""
from pathlib import Path
import subprocess
import sys

root = Path(__file__).resolve().parents[1]
out = root / '.build/greeting-preview'
out.mkdir(parents=True, exist_ok=True)

def interaction_slices():
    """Regenerate `greeting-preview-support.swift` from `Interaction.swift`.

    The fixture needs `hoverState` and `rollingNumber` and nothing else out of
    that file. Copying them by hand is how a preview ends up rendering a version
    of the roll the app no longer has, so the copy is rebuilt from the production
    source here, on every run.
    """
    text = (root / 'Sources/ClaudeBar/Views/Shared/Interaction.swift').read_text()

    def braces(start):
        opening = text.index('{', start)
        depth, index = 1, opening + 1
        while depth:
            depth += (text[index] == '{') - (text[index] == '}')
            index += 1
        return text[start:index]

    starts = [i for i in range(len(text)) if text.startswith('extension View {', i)]
    hover_extension = next(i for i in starts if 'func hoverState' in braces(i))
    roll_extension = next(i for i in starts if 'func rollingNumber' in braces(i))
    parts = [braces(text.index('struct HoverState: ViewModifier {')),
             braces(hover_extension),
             braces(text.index('struct RollingNumberModifier: ViewModifier {')),
             braces(roll_extension)]
    (root / 'Tools/greeting-preview-support.swift').write_text(
        "// Generated by Tools/render-greeting-preview.py from Interaction.swift.\n"
        "// Do not edit: the renderer rebuilds this from the production file every run,\n"
        "// so the fixture cannot drift onto a stub the app does not actually have.\n\n"
        + '\n\n'.join(parts) + '\n')


interaction_slices()


def declaration(path, start):
    text = (root / path).read_text()
    pos = text.index(start)
    opening = text.index('{', pos)
    level = 1
    end = opening + 1
    while level:
        level += (text[end] == '{') - (text[end] == '}')
        end += 1
    return text[pos:end] + "\n"

# `ProductBrandMark` draws the normalised tile glyphs, not the provider-page
# artwork — the two live in different folders on purpose (see
# Tools/gen-brand-marks.py).
brand_marks = root / 'Sources/BrandAssets'
for mark in ('anthropic', 'openai'):
    for variant in ('light', 'dark'):
        assert (brand_marks / f'{mark}-{variant}.png').is_file(), \
            f'{mark}-{variant}.png missing — ProductBrandMark would draw its fallback'

# A plain concatenation, not an f-string: the Swift below is full of braces and
# an f-string would try to read them as fields.
source = ("import AppKit\n@MainActor var fixtureSkyDate = Date()\n@MainActor var fixtureCardWidth: CGFloat = 1100\n"
          + "@MainActor var fixtureSkyMode = \"auto\"\n"
          + "@MainActor var fixtureWeatherRendering = true\n"
          + "@MainActor var fixtureClockPreview: Date? = nil\n"
          + "@MainActor func fixtureBenchOffset() -> TimeInterval { Double(benchClock.tick) * 90 }\n"
          + 'let brandMarks = "' + str(brand_marks) + '"\n'
          + 'let scriptFonts = "' + str(root / 'Sources/Fonts') + '"\n'
          + '''import SwiftUI
final class AppPreferences {
    static let shared = AppPreferences()
    var isDark = false
    var greetingWeatherRendering = true
}
struct SurfaceKey: EnvironmentKey { static let defaultValue = true }
extension EnvironmentValues {
    var surfaceIsVisible: Bool {
        get { self[SurfaceKey.self] }
        set { self[SurfaceKey.self] = newValue }
    }
}
// Static capture: transitions need no adapter or live store. `hoverState` and
// the digit roll are taken from `Interaction.swift` below rather than stubbed,
// so the fixture renders the paths the app actually runs.
enum UsageStats {
    static func formatTokens(_ n: Int) -> String {
        if n >= 1_000_000 { return String(format: "%.2fM", Double(n) / 1_000_000) }
        return n.formatted()
    }
}
''')
source += declaration('Sources/ClaudeBar/Theme/Theme.swift', 'extension Color {')
source += declaration('Sources/ClaudeBar/Theme/Theme.swift', 'enum Theme {')
source += (root / 'Sources/ClaudeBar/Utils/SkyAstronomy.swift').read_text() + '\n'
source += declaration('Sources/ClaudeBar/Utils/WeatherForecastFetcher.swift', 'struct WeatherDay: Equatable, Identifiable {')
source += declaration('Sources/ClaudeBar/Views/Shared/WeatherReadingSky.swift', 'extension WeatherReading.Sky {')
source += (root / 'Sources/ClaudeBar/Utils/GreetingPhrase.swift').read_text() + '\n'
source += declaration('Sources/ClaudeBar/Utils/WeatherFetcher.swift', 'struct WeatherReading: Equatable {')
source += declaration('Sources/ClaudeBar/Utils/CodexQuotaFetcher.swift', 'struct CodexQuotaWindow: Equatable, Identifiable {')
# The Cursor allowance's value types, for the model zone's new Cursor row. The
# whole file, because `PlanUsage` is nested in `CursorUsageFetcher` and its
# `spendText` calls the enum's own `money` helper.
_cursor_fetcher = (root / 'Sources/ClaudeBar/Utils/CursorUsageFetcher.swift').read_text()
# The static renderer only needs the value types and their formatting. Replace
# the two calls that reach the app's credential/network layers with inert
# stand-ins so the file compiles without CursorDB or URLSession machinery.
_cursor_fetcher = _cursor_fetcher.replace(
    'CursorDB.readCredentials()', 'nil as CursorCredentials?')
source += _cursor_fetcher + '\n'
# The fetcher persists its last reading under the app-support directory.
source += (root / 'Sources/Shared/BuildChannel.swift').read_text() + '\n'
source += (root / 'Sources/ClaudeBar/Utils/FilePaths.swift').read_text() + '\n'
# The credential value type the fetcher's guard reads; the standalone struct has
# no SQLite in it, so the fixture can carry it without the database layer.
source += declaration('Sources/ClaudeBar/Utils/CursorDB.swift', 'struct CursorCredentials: Equatable {')
source += (root / 'Sources/ClaudeBar/Views/Shared/WeatherBackdrop.swift').read_text() + '\n'
# `ImageRenderer` cannot capture an MTKView, so the sky goes through the
# production still path: the same shader, drawn once into an image.
for atmosphere in ['SkyScene', 'AtmosphereShader', 'AtmosphereRenderer', 'AtmosphereView', 'GreetingScript']:
    source += (root / f'Sources/ClaudeBar/Views/Shared/Atmosphere/{atmosphere}.swift').read_text() + '\n'
# The two clients' separator rule between them.
source += declaration('Sources/ClaudeBar/Theme/Theme.swift', 'struct VerticalHairline: View {')
# The fused client mark. `ProductBrandMark` is its artwork, so the preview
# exercises the production drawing rather than a stand-in.
# `Interaction.swift` is mostly controls the fixture does not build, so take the
# two pieces it uses — the hover observer and the digit roll — rather than the
# whole file, which would drag the control plate and `AppGlyph` in behind
# it. Regenerated on every run, from the production file, so the fixture cannot
# quietly keep using a copy the app has moved on from.
source += (root / 'Tools/greeting-preview-support.swift').read_text() + '\n'
source += declaration('Sources/ClaudeBar/Views/Shared/LucideHardwareGeometry.swift', 'enum LucideHardwareGeometry {')
source += declaration('Sources/ClaudeBar/Views/Shared/InstrumentGlyph.swift', 'struct InstrumentGlyph: View, Animatable {')
source += declaration('Sources/ClaudeBar/Views/Shared/InstrumentGlyph.swift', 'struct InstrumentBadge: View {')
source += (root / 'Sources/ClaudeBar/Views/Shared/LucideHardwarePaths.swift').read_text() + '\n'
# The allowance probe reads the account's cycle out of the store that owns it;
# the fixture only builds the value types, so the store is an inert stand-in.
source += '''
final class CursorUsageStore {
    @MainActor static let shared = CursorUsageStore()
    private init() {}
    var plan: CursorUsageFetcher.PlanUsage? { nil }
}
enum ScrollHoverGate { @MainActor static var isDeferring = false }
struct ScrollHoverGateModifier: ViewModifier {
    func body(content: Content) -> some View { content }
}
// The `@State` stubs above have no setter callback, so the sheet is a still
// fixture: its own assignments are inert.
enum Unused {}
'''
source += declaration('Sources/ClaudeBar/Views/Shared/ProductBrandMark.swift', 'struct ProductBrandMark: View {')

source += (root / 'Sources/ClaudeBar/Views/Shared/CodexModelMark.swift').read_text() + '\n'
# The lane draws `InstrumentGlyph`'s `.tokens` mark through `Theme.hairline`;
# both come in above. `detailed` is what makes the gauge a reading here.
# ImageRenderer cannot capture AppKit-backed Liquid Glass. The static matrix
# exercises the production macOS 15 material fallback, with identical content.
# `cardWidth` is pinned because a one-shot render never sees the geometry
# callback that sizes the greeting in the app.
# The card's instruments (weather glyphs, forecast ribbon, sun path, sill
# gauges) are self-contained views; the whole file comes in as is.
source += (root / 'Sources/ClaudeBar/Views/Shared/GreetingInstruments.swift').read_text() + '\n'
sheet = (root / 'Sources/ClaudeBar/Views/Shared/GreetingCard.swift').read_text()
if '--bench-baseline' in sys.argv:
    # Every part rebuilt on every change, as before `Unchanged` existed.
    sheet = sheet.replace('static func == (lhs: Self, rhs: Self) -> Bool { lhs.key == rhs.key }',
                          'static func == (lhs: Self, rhs: Self) -> Bool { false }')
sheet = sheet.replace(
    """            let clockZone: String? = liveWeather ? reading?.timezone : nil
            let clockPreview: Date? = manual ? manualDate : (timeOffset == 0 || !liveWeather ? nil : sceneDate)
""", "")
# The clock and the mode toggle move into a helper: the fixture's whole `ZStack`
# literal is what the type checker cannot handle in reasonable time once the
# sky branch grew a second condition.
sheet = sheet.replace(
    """            VStack(alignment: .leading, spacing: 8) {
                GreetingClock(ink: topLeftInk, timezone: clockZone, preview: clockPreview)
                SkyModeToggle(skyMode: skyMode, rendering: self.weatherRendering, ink: topLeftInk,
                              setManual: { setManual($0, scene: scene) },
                              setRendering: { AppPreferences.shared.greetingWeatherRendering = $0 })
                    .frame(width: m.skyToggleWidth, alignment: .leading)
            }
            .padding(.leading, m.margin)
            .padding(.top, m.top)
            .modifier(StatusArrival(arrived: arrived, delay: 1.1, reduceMotion: reduceMotion))
""",
    """            topInstruments(ink: topLeftInk, m: m, layout: layout)
""")
# The clock and the mode toggle move into a helper: the fixture's whole `ZStack`
# literal is what the type checker cannot handle in reasonable time once the
# sky branch grew a second condition.
sheet = sheet.replace("    // MARK: - Sky",
"""    private func topInstruments(ink: Color, m: Metrics, layout: GreetingTypesetter.Layout) -> some View {
        VStack(alignment: .leading, spacing: 8) {
            GreetingClock(ink: ink, timezone: liveWeather ? reading?.timezone : nil,
                          preview: manual ? manualDate : (timeOffset == 0 || !liveWeather ? nil : sceneDate))
            SkyModeToggle(skyMode: skyMode, rendering: self.weatherRendering, ink: ink,
                          setManual: { setManual($0, scene: makeScene()) },
                          setRendering: { _ in })
                .frame(width: m.skyToggleWidth, alignment: .leading)
        }
        .padding(.leading, m.margin)
        .padding(.top, m.top)
        .modifier(StatusArrival(arrived: arrived, delay: 1.1, reduceMotion: reduceMotion))
    }

    // MARK: - Sky""")
source += (sheet[sheet.index('struct GreetingStatusSheet: View {'):]
    .replace('@State private var arrived = false', '@State private var arrived = true')
    .replace('@State private var cardWidth: CGFloat = 1100', '@State private var cardWidth: CGFloat = fixtureCardWidth')
      # The old template replayed a live @State init through a `.replace` on the
      # body; those calls no longer exist, and `self.sensoryFeedback(...)` on a
      # freshly rewritten body is what the type checker chokes on.
    .replace('skyDate = Date()', 'skyDate = fixtureSkyDate')
    .replace('.sensoryFeedback(.levelChange, trigger: Int(timeOffset / 3600))', '')
    .replace('.sensoryFeedback(.levelChange, trigger: manual && dragBase != nil ? Int(minutes / 60) : -1)', '')
    .replace('.sensoryFeedback(.selection, trigger: pinnedDay)', '')
    .replace('.sensoryFeedback(.alignment, trigger: rewrites)', '')
    .replace('.onChange(of: typeface) {', '.onChange(of: typeface) { _ in')
      # The type checker times out on the fixture's whole modifier chain once the
      # `onChange` closures lose their parameter lists; pin the one change here.
    .replace("        .onChange(of: reading?.sky) { old, new in\n            // A rainbow is earned: rain that has just cleared, with the sun low\n            // enough (below 42°) for the bow to stand above the horizon.\n            if let old, [.rain, .drizzle, .thunder].contains(old), let new, [.clear, .partly].contains(new) {\n                rainbowUntil = Date().addingTimeInterval(1800)\n            }\n        }\n", '')
    .replace('@State private var skyDate = Date()', '@State private var skyDate = fixtureSkyDate')
    .replace('skyDate = Date()', 'skyDate = fixtureSkyDate')
    .replace('context.date', 'fixtureSkyDate')
    .replace('else if #available(macOS 26.0, *) {', 'else if #available(macOS 26.0, *), false {')
    .replace('        return skyDate.addingTimeInterval(timeOffset)',
             '        return skyDate.addingTimeInterval(timeOffset + fixtureBenchOffset())'))
# A raw literal so the Swift string interpolations below stay single-backslash
# Swift (`\(x)`), which is what the production text wants; a plain `'''…'''`
# would read them as Python escapes and warn on every run.
source += r'''
@main struct Probe {
    @MainActor static func main() throws {
        _ = NSApplication.shared
        guard AtmosphereGPU.loadNow() != nil else { fatalError("Metal atmosphere unavailable") }
        AtmosphereSurface.stills = true
        // No app bundle here: read the brand PNGs from the repo's own copy, or
        // the mark silently renders its missing-asset fallback.
        ProductBrandMark.resourceRoot = URL(fileURLWithPath: brandMarks)
        GreetingScript.resourceRoot = URL(fileURLWithPath: scriptFonts)
        let out = URL(fileURLWithPath: CommandLine.arguments[1])
        if CommandLine.arguments.contains("--bench") { benchUpdates(); return }
        let review = CommandLine.arguments.contains("--weather-review")
        for mode in (review ? ["auto", "manual"] : ["auto", "manual", "bare"]) {
        // The sheet reads its sky mode through @AppStorage; the argument
        // domain is volatile, so the fixture never writes a preference.
        UserDefaults.standard.setVolatileDomain(["greeting.skyMode": mode == "manual" ? "manual" : "auto",
                                                 "greeting.manualWeather": "snow",
                                                 "greeting.manualMinutes": 17.0 * 60 + 55],
                                                forName: UserDefaults.argumentDomain)
        // "bare": 天气渲染关着，但天空没有挑过任何一层——就是默认的贴图。
        fixtureWeatherRendering = mode != "bare"
        for dark in (review ? [false] : [false, true]) {
            AppPreferences.shared.isDark = dark
            for width in [1100.0, 620.0] {
                fixtureCardWidth = width
                // Light auto also writes the sunny card once per selectable
                // face, so a face whose proportions break the layout shows up.
                let faces = !review && mode == "auto" && !dark ? GreetingTypeface.allCases.map { "face-" + $0.rawValue } : []
                for scene in (mode == "manual" ? ["sun"] : ["sun", "rain", "heavy", "thunder", "night", "cloud", "snow", "fog", "empty"]) + faces {
                    let typeface = scene.hasPrefix("face-") ? GreetingTypeface(rawValue: String(scene.dropFirst(5)))! : .standard
                    fixtureSkyDate = ISO8601DateFormatter().date(from: scene == "night" ? "2026-09-28T13:00:00Z" : "2026-09-28T02:17:01Z")!
                    let empty = scene == "empty"
                    var weather = WeatherReading(place: "广州 · 天河区", temperatureC: 29, feelsLikeC: 32,
                        conditionCode: scene == "rain" ? 296 : scene == "heavy" ? 308 : scene == "thunder" ? 389 : scene == "fog" ? 248 : scene == "cloud" ? 119 : scene == "snow" ? 338 : 113, conditionText: "多云", highC: 32, lowC: 25, humidity: 68,
                        windKph: 8, windDirection: "东南", isDay: scene != "night", sunrise: "06:18", sunset: "18:22",
                        rainChance: ["heavy", "thunder"].contains(scene) ? 90 : 20, observedAt: fixtureSkyDate, latitude: 23.13, longitude: 113.26, timezone: "Asia/Shanghai", source: "Open-Meteo")
                    weather.hourlySource = "Open-Meteo"
                    weather.hourly = (1...6).map { i in
                        WeatherReading.Hour(date: fixtureSkyDate.addingTimeInterval(Double(i) * 3600),
                            temperature: Double(29 - i),
                            precipitation: ["rain", "heavy", "thunder"].contains(scene) ? [1.2, 2.8, 4.1, 2.0, 0.5, 0][i-1] : 0,
                            rainChance: ["rain", "heavy", "thunder"].contains(scene) ? 85 : 10,
                            wind: 8)
                    }
                    var calendar = Calendar(identifier: .gregorian)
                    calendar.timeZone = TimeZone(identifier: "Asia/Shanghai")!
                    let start = calendar.startOfDay(for: fixtureSkyDate)
                    weather.forecast = (0..<6).map { i in
                        let date = calendar.date(byAdding: .day, value: i, to: start)!
                        return WeatherDay(date: date, code: [2, 61, 95, 3, 0, 2][i], high: Double(32-i), low: Double(25-i),
                            rainChance: [20, 80, 95, 10, 0, 15][i], wind: Double(8+i*3),
                            sunrise: date.addingTimeInterval(6*3600+18*60), sunset: date.addingTimeInterval(18*3600+22*60))
                    }
                    let windows = [CodexQuotaWindow(label: "5 小时", usedPercent: 82,
                        resetsAt: Date().addingTimeInterval(8360)),
                        CodexQuotaWindow(label: "7 天", usedPercent: 50,
                        resetsAt: Date().addingTimeInterval(272160))]
                    let card = GreetingStatusSheet(name: "Xiajun Wang", ccModel: empty ? "未配置" : "deepseek-v4.1-flash",
                        ccProvider: "Aibox", codexModel: empty ? "默认模型" : "gpt-6-astra",
                        codexProvider: "OpenAI",
                        tokens: empty ? 0 : 12840000, yesterdayTokens: empty ? 0 : 9640000,
                        calls: empty ? 0 : 286, spend: empty ? "暂无报价" : "¥404.70",
                        windows: empty ? [] : windows, quotaLoading: false,
                        quotaNote: empty ? "Codex 额度查询失败" : nil,
                        cursorPlan: empty ? nil : CursorUsageFetcher.PlanUsage(usedPercent: 46, apiPercentUsed: 40,
                            autoPercentUsed: 52, totalSpendCents: 920, limitCents: 2000, includedSpendCents: 920,
                            bonusSpendCents: nil, billingCycleEnd: Date().addingTimeInterval(9 * 86400)),
                        cursorLoading: false, cursorNote: empty ? "未读取到 Cursor 额度" : nil,
                        reading: empty ? nil : weather, city: "广州", weatherLoading: false,
                        weatherNote: nil, typeface: typeface, language: typeface.supportsChinese ? .chinese : .english, weatherRendering: fixtureWeatherRendering, refreshWeather: {}, refreshQuota: {}, refreshCursor: {},
                        showModels: {}, showUsage: {})
                        .environment(\.colorScheme, dark ? .dark : .light)
                        .frame(width: width).padding(24).background(Theme.bgPrimary)
                    if scene == "sun" && mode == "auto" {
                        // The forecast ribbon with a day focused, as hover or a
                        // pin leaves it — the one state a static card render
                        // cannot reach, since focus is the sheet's own @State.
                        let ribbon = ForecastRibbon(days: weather.forecast, zone: TimeZone(identifier: "Asia/Shanghai")!,
                            ink: .white, vivid: true, focus: weather.forecast[2].date, pinned: weather.forecast[2].date,
                            arrived: true, hover: { _ in }, toggle: { _ in }, move: { _ in }, clear: {})
                            .frame(width: width == 620 ? 236 : 300, height: 80)
                            .padding(20).background(Color(hex: 0x21406E))
                        let render = ImageRenderer(content: ribbon)
                        render.scale = 2
                        if let image = render.cgImage, let png = NSBitmapImageRep(cgImage: image).representation(using: .png, properties: [:]) {
                            try png.write(to: out.appendingPathComponent("ribbon-\(dark ? "dark" : "light")-\(Int(width)).png"))
                        }
                    }
                    let renderer = ImageRenderer(content: card)
                    renderer.scale = 2
                    guard let image = renderer.cgImage,
                          let png = NSBitmapImageRep(cgImage: image).representation(using: .png, properties: [:])
                    else { fatalError("Render failed") }
                    let name = "\(mode.hasPrefix("face-") ? "" : mode + "-")\(dark ? "dark" : "light")-\(Int(width))-\(scene).png"
                    try png.write(to: out.appendingPathComponent(name))
                }
            }
        }
        print("Rendered synthetic fixture views to \(out.path)")
        }
    }
}
'''
# `--bench`: time one SwiftUI update of the live card (body, diff, layout and
# display) the way a drag or a glide drives it — every frame changes an input
# of the sheet, so its whole body is evaluated again.
source += '''
@MainActor @Observable final class BenchModel { var tick = 0 }
@MainActor let benchClock = BenchModel()
struct BenchHost: View {
    let model: BenchModel
    let weather: WeatherReading
    var body: some View {
        GreetingStatusSheet(name: "Xiajun Wang", ccModel: "deepseek-v4.1-flash", ccProvider: "Aibox",
            codexModel: "gpt-6-astra", codexProvider: "OpenAI",
            tokens: 12840000 + model.tick, yesterdayTokens: 9640000, calls: 286, spend: "¥404.70",
            windows: [CodexQuotaWindow(label: "5 小时", usedPercent: 82, resetsAt: Date().addingTimeInterval(8360))],
            quotaLoading: false, quotaNote: nil, cursorPlan: nil, cursorLoading: false, cursorNote: nil,
            reading: weather, city: "广州", weatherLoading: false, weatherNote: nil,
            refreshWeather: {}, refreshQuota: {}, refreshCursor: {}, showModels: {}, showUsage: {})
            .frame(width: 1100)
            // The sky's own cost is measured by bench-atmosphere.py; paused,
            // it cannot interleave its draws with the commits timed here.
            .environment(\\.surfaceIsVisible, false)
    }
}
@MainActor func benchUpdates() {
    AtmosphereSurface.stills = false
    fixtureSkyDate = Date()
    var weather = WeatherReading(place: "广州 · 天河区", temperatureC: 29, feelsLikeC: 32, conditionCode: 113,
        conditionText: "晴", highC: 32, lowC: 25, humidity: 68, windKph: 8, windDirection: "东南", isDay: true,
        sunrise: "06:18", sunset: "18:22", rainChance: 20, observedAt: Date(), latitude: 23.13, longitude: 113.26,
        timezone: "Asia/Shanghai", source: "Open-Meteo")
    let start = Calendar.current.startOfDay(for: Date())
    weather.forecast = (0..<6).map { i in
        let date = start.addingTimeInterval(Double(i) * 86400)
        return WeatherDay(date: date, code: [2, 61, 95, 3, 0, 2][i], high: Double(32 - i), low: Double(25 - i),
            rainChance: [20, 80, 95, 10, 0, 15][i], wind: Double(8 + i * 3),
            sunrise: date.addingTimeInterval(6 * 3600), sunset: date.addingTimeInterval(18 * 3600))
    }
    let model = BenchModel()
    let host = NSHostingView(rootView: BenchHost(model: model, weather: weather))
    let window = NSWindow(contentRect: NSRect(x: 0, y: 0, width: 1100, height: 520), styleMask: [.borderless],
                          backing: .buffered, defer: false)
    window.contentView = host
    window.orderFrontRegardless()
    var update: [Double] = [], commit: [Double] = []
    let total = Int(ProcessInfo.processInfo.environment["BENCH_N"] ?? "") ?? 240
    let unpaced = ProcessInfo.processInfo.environment["BENCH_PACE"] == "0"
    for i in 0..<total {
        // Paced like a 60 Hz display, so the commit measures work rather than
        // waiting on surfaces the window server has not released yet.
        // BENCH_PACE=0 runs back to back without committing: the CPU stays at
        // one clock, so builds can be compared on update cost alone.
        if !unpaced { RunLoop.current.run(until: Date().addingTimeInterval(1.0 / 60)) }
        let a = CACurrentMediaTime()
        // A drag: only the sky's time moves (90 s a frame), as `timeOffset` does.
        benchClock.tick += 1
        host.layoutSubtreeIfNeeded()
        let b = CACurrentMediaTime()
        if !unpaced { host.displayIfNeeded(); CATransaction.flush() }
        let c = CACurrentMediaTime()
        if i >= min(40, total / 4) { update.append((b - a) * 1000); commit.append((c - b) * 1000) }
    }
    func stats(_ label: String, _ v: [Double]) {
        let v = v.sorted()
        print(String(format: "%@ p25 %.2f ms, median %.2f ms, p90 %.2f ms", label, v[v.count / 4], v[v.count / 2], v[v.count * 9 / 10]))
    }
    stats("card update (body + layout):", update)
    stats("card commit (display list):  ", commit)
}
'''
path = out / 'Probe.swift'
path.write_text(source)
binary = out / 'probe'
bench = '--bench' in sys.argv or '--bench-baseline' in sys.argv
subprocess.run(['swiftc'] + (['-O'] if bench else []) + ['-parse-as-library', '-D', 'CLAUDEBAR_DEV', '-target', 'arm64-apple-macos15.0',
                str(path), '-o', str(binary)], check=True)
subprocess.run([str(binary), str(out)] + (['--bench'] if bench else ['--weather-review'] if '--weather-review' in sys.argv else []), check=True)
