#!/usr/bin/env python3
"""Render the production status sheet at wide/narrow widths in both themes.
Only the store-dependent wrapper is omitted. Fixtures are synthetic; no account
files, live services or persistent preferences are read or changed.
"""
from pathlib import Path
import subprocess

root = Path(__file__).resolve().parents[1]
out = root / '.build/greeting-preview'
out.mkdir(parents=True, exist_ok=True)

def interaction_slices():
    """Regenerate `greeting-preview-support.swift` from `Interaction.swift`.

    The fixture needs `hoverState` and `rollingNumber` and nothing else out of
    that file. Copying them by hand is how a preview ends up rendering a version
    of the roll the app no longer has, so the copy is rebuilt from the production
    source here, on every run.
    """
    text = (root / 'Sources/ClaudeBar/Views/Shared/Interaction.swift').read_text()

    def braces(start):
        opening = text.index('{', start)
        depth, index = 1, opening + 1
        while depth:
            depth += (text[index] == '{') - (text[index] == '}')
            index += 1
        return text[start:index]

    starts = [i for i in range(len(text)) if text.startswith('extension View {', i)]
    hover_extension = next(i for i in starts if 'func hoverState' in braces(i))
    roll_extension = next(i for i in starts if 'func rollingNumber' in braces(i))
    parts = [braces(text.index('struct HoverState: ViewModifier {')),
             braces(hover_extension),
             braces(text.index('struct RollingNumberModifier: ViewModifier {')),
             braces(roll_extension)]
    (root / 'Tools/greeting-preview-support.swift').write_text(
        "// Generated by Tools/render-greeting-preview.py from Interaction.swift.\n"
        "// Do not edit: the renderer rebuilds this from the production file every run,\n"
        "// so the fixture cannot drift onto a stub the app does not actually have.\n\n"
        + '\n\n'.join(parts) + '\n')


interaction_slices()


def declaration(path, start):
    text = (root / path).read_text()
    pos = text.index(start)
    opening = text.index('{', pos)
    level = 1
    end = opening + 1
    while level:
        level += (text[end] == '{') - (text[end] == '}')
        end += 1
    return text[pos:end] + "\n"

# `ProductBrandMark` draws the normalised tile glyphs, not the provider-page
# artwork — the two live in different folders on purpose (see
# Tools/gen-brand-marks.py).
brand_marks = root / 'Sources/BrandAssets'
for mark in ('anthropic', 'openai'):
    for variant in ('light', 'dark'):
        assert (brand_marks / f'{mark}-{variant}.png').is_file(), \
            f'{mark}-{variant}.png missing — ProductBrandMark would draw its fallback'

# A plain concatenation, not an f-string: the Swift below is full of braces and
# an f-string would try to read them as fields.
source = ("import AppKit\n@MainActor var fixtureSkyDate = Date()\n"
          + 'let brandMarks = "' + str(brand_marks) + '"\n'
          + '''import SwiftUI
final class AppPreferences {
    static let shared = AppPreferences()
    var isDark = false
}
struct SurfaceKey: EnvironmentKey { static let defaultValue = true }
extension EnvironmentValues {
    var surfaceIsVisible: Bool {
        get { self[SurfaceKey.self] }
        set { self[SurfaceKey.self] = newValue }
    }
}
// Static capture: transitions need no adapter or live store. `hoverState` and
// the digit roll are taken from `Interaction.swift` below rather than stubbed,
// so the fixture renders the paths the app actually runs.
enum UsageStats {
    static func formatTokens(_ n: Int) -> String {
        if n >= 1_000_000 { return String(format: "%.2fM", Double(n) / 1_000_000) }
        return n.formatted()
    }
}
''')
source += declaration('Sources/ClaudeBar/Theme/Theme.swift', 'extension Color {')
source += declaration('Sources/ClaudeBar/Theme/Theme.swift', 'enum Theme {')
source += (root / 'Sources/ClaudeBar/Utils/SkyAstronomy.swift').read_text() + '\n'
source += declaration('Sources/ClaudeBar/Utils/WeatherForecastFetcher.swift', 'struct WeatherDay: Equatable, Identifiable {')
source += (root / 'Sources/ClaudeBar/Views/Shared/WeatherExplorer.swift').read_text() + '\n'
source += (root / 'Sources/ClaudeBar/Utils/GreetingPhrase.swift').read_text() + '\n'
source += declaration('Sources/ClaudeBar/Utils/WeatherFetcher.swift', 'struct WeatherReading: Equatable {')
source += declaration('Sources/ClaudeBar/Utils/CodexQuotaFetcher.swift', 'struct CodexQuotaWindow: Equatable, Identifiable {')
source += (root / 'Sources/ClaudeBar/Views/Shared/WeatherBackdrop.swift').read_text() + '\n'
# `presented` is pinned so the fixture captures the arrived state — the same
# frame a user sees at rest and the one a hover replays into.
source += (root / 'Sources/ClaudeBar/Views/Shared/SkyGreeting.swift').read_text().replace('@State private var presented = false', '@State private var presented = true') + '\n'
# The two clients' separator rule between them.
source += declaration('Sources/ClaudeBar/Theme/Theme.swift', 'struct VerticalHairline: View {')
# The fused client mark. `ProductBrandMark` is its artwork, so the preview
# exercises the production drawing rather than a stand-in.
# `Interaction.swift` is mostly controls the fixture does not build, so take the
# two pieces it uses — the hover observer and the digit roll — rather than the
# whole file, which would drag `InstrumentButtonStyle` and `AppGlyph` in behind
# it. Regenerated on every run, from the production file, so the fixture cannot
# quietly keep using a copy the app has moved on from.
source += (root / 'Tools/greeting-preview-support.swift').read_text() + '\n'
source += declaration('Sources/ClaudeBar/Views/Shared/LucideHardwareGeometry.swift', 'enum LucideHardwareGeometry {')
source += declaration('Sources/ClaudeBar/Views/Shared/InstrumentGlyph.swift', 'struct InstrumentGlyph: View, Animatable {')
source += declaration('Sources/ClaudeBar/Views/Shared/InstrumentGlyph.swift', 'struct InstrumentBadge: View {')
source += (root / 'Sources/ClaudeBar/Views/Shared/LucideHardwarePaths.swift').read_text() + '\n'
source += declaration('Sources/ClaudeBar/Views/Shared/ProductBrandMark.swift', 'struct ProductBrandMark: View {')

source += (root / 'Sources/ClaudeBar/Views/Shared/CodexModelMark.swift').read_text() + '\n'
# The lane draws `InstrumentGlyph`'s `.tokens` mark through `Theme.hairline`;
# both come in above. `detailed` is what makes the gauge a reading here.
sheet = (root / 'Sources/ClaudeBar/Views/Shared/GreetingCard.swift').read_text()
source += sheet[sheet.index('struct GreetingStatusSheet: View {'):].replace('@State private var arrived = false', '@State private var arrived = true').replace('skyDate = Date()', 'skyDate = fixtureSkyDate')
source += '''
@main struct Probe {
    @MainActor static func main() throws {
        _ = NSApplication.shared
        // No app bundle here: read the brand PNGs from the repo's own copy, or
        // the mark silently renders its missing-asset fallback.
        ProductBrandMark.resourceRoot = URL(fileURLWithPath: brandMarks)
        let out = URL(fileURLWithPath: CommandLine.arguments[1])
        for dark in [false, true] {
            AppPreferences.shared.isDark = dark
            for width in [1100.0, 620.0] {
                for scene in ["sun", "rain", "night", "cloud", "snow", "empty"] {
                    fixtureSkyDate = ISO8601DateFormatter().date(from: scene == "night" ? "2026-09-27T13:00:00Z" : "2026-09-27T04:00:00Z")!
                    let empty = scene == "empty"
                    var weather = WeatherReading(place: "广州", temperatureC: 29, feelsLikeC: 32,
                        conditionCode: scene == "rain" ? 296 : scene == "cloud" ? 119 : scene == "snow" ? 338 : 113, conditionText: "多云", highC: 32, lowC: 25, humidity: 68,
                        windKph: 8, windDirection: "东南", isDay: scene != "night", sunrise: "06:18", sunset: "18:22",
                        rainChance: 20, observedAt: Date(), latitude: 23.13, longitude: 113.26, timezone: "Asia/Shanghai", source: "Open-Meteo")
                    var calendar = Calendar(identifier: .gregorian)
                    calendar.timeZone = TimeZone(identifier: "Asia/Shanghai")!
                    let start = calendar.startOfDay(for: Date())
                    weather.forecast = (0..<6).map { i in
                        let date = calendar.date(byAdding: .day, value: i, to: start)!
                        return WeatherDay(date: date, code: [2, 61, 95, 3, 0, 2][i], high: Double(32-i), low: Double(25-i),
                            rainChance: [20, 80, 95, 10, 0, 15][i], wind: Double(8+i*3),
                            sunrise: date.addingTimeInterval(6*3600+18*60), sunset: date.addingTimeInterval(18*3600+22*60))
                    }
                    let windows = [CodexQuotaWindow(label: "5 小时", usedPercent: 16,
                        resetsAt: Date().addingTimeInterval(8360)),
                        CodexQuotaWindow(label: "7 天", usedPercent: 42,
                        resetsAt: Date().addingTimeInterval(272160))]
                    let card = GreetingStatusSheet(name: "王夏军", ccModel: empty ? "未配置" : "claude-sonnet-4-6",
                        ccProvider: "Anthropic", codexModel: empty ? "默认模型" : "gpt-5.4",
                        codexProvider: "OpenAI", balance: empty ? "未提供余额" : "128.50 Credits",
                        tokens: empty ? 0 : 12840000, yesterdayTokens: empty ? 0 : 9640000,
                        calls: empty ? 0 : 286, spend: empty ? "暂无报价" : "¥404.70",
                        windows: empty ? [] : windows, quotaLoading: false,
                        quotaNote: empty ? "Codex 额度查询失败" : nil,
                        reading: empty ? nil : weather, city: "广州", weatherLoading: false,
                        weatherNote: nil, refreshWeather: {}, refreshQuota: {},
                        showModels: {}, showUsage: {})
                        .environment(\\.colorScheme, dark ? .dark : .light)
                        .frame(width: width).padding(24).background(Theme.bgPrimary)
                    if width == 620 && scene == "sun" {
                        for future in [false, true] {
                            let detail = WeatherDetails(reading: weather, selectedDate: .constant(future ? weather.forecast[5].date : nil),
                                palette: SkyPalette(sky: .clear, night: dark), skyDate: fixtureSkyDate,
                                weatherLoading: false, weatherNote: future ? nil : "天气更新失败，显示上次读数", close: {})
                            let render = ImageRenderer(content: detail)
                            render.scale = 2
                            if let image = render.cgImage, let png = NSBitmapImageRep(cgImage: image).representation(using: .png, properties: [:]) {
                                try png.write(to: out.appendingPathComponent("detail-\\(dark ? "dark" : "light")-\\(future ? "day5" : "current").png"))
                            }
                        }
                    }
                    let renderer = ImageRenderer(content: card)
                    renderer.scale = 2
                    guard let image = renderer.cgImage,
                          let png = NSBitmapImageRep(cgImage: image).representation(using: .png, properties: [:])
                    else { fatalError("Render failed") }
                    let name = "\\(dark ? "dark" : "light")-\\(Int(width))-\\(scene).png"
                    try png.write(to: out.appendingPathComponent(name))
                }
            }
        }
        print("Rendered 24 synthetic fixture views to \\(out.path)")
    }
}
'''
path = out / 'Probe.swift'
path.write_text(source)
binary = out / 'probe'
subprocess.run(['swiftc', '-parse-as-library', '-target', 'arm64-apple-macos15.0', str(path), '-o', str(binary)], check=True)
subprocess.run([str(binary), str(out)], check=True)
