import Foundation

struct EnvConfig: Codable, Equatable {
    var ANTHROPIC_AUTH_TOKEN: String = ""
    var ANTHROPIC_BASE_URL: String = ""
    var ANTHROPIC_MODEL: String = ""
    var CLAUDE_CODE_MAX_CONTEXT_TOKENS: String = ""
    var DISABLE_COMPACT: String = ""
    var GITHUB_PERSONAL_ACCESS_TOKEN: String = ""
    var CLAUDE_CODE_DISABLE_EXPERIMENTAL_BETAS: String = ""
    var ANTHROPIC_DEFAULT_OPUS_MODEL: String = ""
    var ANTHROPIC_DEFAULT_OPUS_MODEL_NAME: String = ""
    var ANTHROPIC_DEFAULT_SONNET_MODEL: String = ""
    var ANTHROPIC_DEFAULT_SONNET_MODEL_NAME: String = ""
    var ANTHROPIC_DEFAULT_HAIKU_MODEL: String = ""
    var ANTHROPIC_DEFAULT_HAIKU_MODEL_NAME: String = ""
    var ANTHROPIC_DEFAULT_FABLE_MODEL: String = ""
    var ANTHROPIC_DEFAULT_FABLE_MODEL_NAME: String = ""
    var CLAUDE_CODE_AUTO_COMPACT_WINDOW: String = ""

    init(ANTHROPIC_AUTH_TOKEN: String = "", ANTHROPIC_BASE_URL: String = "", ANTHROPIC_MODEL: String = "", CLAUDE_CODE_MAX_CONTEXT_TOKENS: String = "", DISABLE_COMPACT: String = "", GITHUB_PERSONAL_ACCESS_TOKEN: String = "", CLAUDE_CODE_DISABLE_EXPERIMENTAL_BETAS: String = "", ANTHROPIC_DEFAULT_OPUS_MODEL: String = "", ANTHROPIC_DEFAULT_OPUS_MODEL_NAME: String = "", ANTHROPIC_DEFAULT_SONNET_MODEL: String = "", ANTHROPIC_DEFAULT_SONNET_MODEL_NAME: String = "", ANTHROPIC_DEFAULT_HAIKU_MODEL: String = "", ANTHROPIC_DEFAULT_HAIKU_MODEL_NAME: String = "", ANTHROPIC_DEFAULT_FABLE_MODEL: String = "", ANTHROPIC_DEFAULT_FABLE_MODEL_NAME: String = "", CLAUDE_CODE_AUTO_COMPACT_WINDOW: String = "") {
        self.ANTHROPIC_AUTH_TOKEN = ANTHROPIC_AUTH_TOKEN
        self.ANTHROPIC_BASE_URL = ANTHROPIC_BASE_URL
        self.ANTHROPIC_MODEL = ANTHROPIC_MODEL
        self.CLAUDE_CODE_MAX_CONTEXT_TOKENS = CLAUDE_CODE_MAX_CONTEXT_TOKENS
        self.DISABLE_COMPACT = DISABLE_COMPACT
        self.GITHUB_PERSONAL_ACCESS_TOKEN = GITHUB_PERSONAL_ACCESS_TOKEN
        self.CLAUDE_CODE_DISABLE_EXPERIMENTAL_BETAS = CLAUDE_CODE_DISABLE_EXPERIMENTAL_BETAS
        self.ANTHROPIC_DEFAULT_OPUS_MODEL = ANTHROPIC_DEFAULT_OPUS_MODEL
        self.ANTHROPIC_DEFAULT_OPUS_MODEL_NAME = ANTHROPIC_DEFAULT_OPUS_MODEL_NAME
        self.ANTHROPIC_DEFAULT_SONNET_MODEL = ANTHROPIC_DEFAULT_SONNET_MODEL
        self.ANTHROPIC_DEFAULT_SONNET_MODEL_NAME = ANTHROPIC_DEFAULT_SONNET_MODEL_NAME
        self.ANTHROPIC_DEFAULT_HAIKU_MODEL = ANTHROPIC_DEFAULT_HAIKU_MODEL
        self.ANTHROPIC_DEFAULT_HAIKU_MODEL_NAME = ANTHROPIC_DEFAULT_HAIKU_MODEL_NAME
        self.ANTHROPIC_DEFAULT_FABLE_MODEL = ANTHROPIC_DEFAULT_FABLE_MODEL
        self.ANTHROPIC_DEFAULT_FABLE_MODEL_NAME = ANTHROPIC_DEFAULT_FABLE_MODEL_NAME
        self.CLAUDE_CODE_AUTO_COMPACT_WINDOW = CLAUDE_CODE_AUTO_COMPACT_WINDOW
    }
}
